name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ip-10-0-8-91

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: ${{ secrets.REGION }}

      - name: Log in to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.REGION }} | docker login --username AWS --password-stdin 207567792559.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.REPO }} .

      - name: Tag Docker image
        run: |
          docker tag ${{ secrets.REPO }}:latest 207567792559.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.REPO }}:latest

      - name: Push Docker image to AWS ECR
        run: |
          docker push 207567792559.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.REPO }}:latest
